import type { Metadata } from 'next';
import Link from 'next/link';
import { BetsNav } from '../../../components/bets/BetsNav';

export const metadata: Metadata = {
  title: 'Long-Term Strategic Models | Methodology & Formulation | Kosh',
  description:
    'Mathematical formulations and multi-factor quality-growth scoring specifications for long-term equity compounders.',
  alternates: { canonical: '/bets/long-term' },
};

interface StrategicSetup {
  ticker: string;
  name: string;
  sector: string;
  compositeScore: number;
  roe: number;
  debtToEquity: number;
  pegRatio: number;
  salesCagr3Y: number;
  fiiDiiStake: string;
  thesis: string;
}

const SAMPLE_STRATEGIC_SETUPS: StrategicSetup[] = [
  {
    ticker: 'LTIM',
    name: 'LTIMindtree Ltd',
    sector: 'Information Technology',
    compositeScore: 92,
    roe: 26.4,
    debtToEquity: 0.04,
    pegRatio: 1.15,
    salesCagr3Y: 18.2,
    fiiDiiStake: '38.6% (+1.2% QoQ)',
    thesis: 'Net-cash balance sheet with superior capital efficiency, multi-quarter deal ramp-ups in BFSI, and PEG below 1.2x.',
  },
  {
    ticker: 'TITAN',
    name: 'Titan Company Ltd',
    sector: 'Consumer Discretionary',
    compositeScore: 88,
    roe: 31.8,
    debtToEquity: 0.42,
    pegRatio: 1.45,
    salesCagr3Y: 24.1,
    fiiDiiStake: '32.4% (+0.6% QoQ)',
    thesis: 'Structural market share gains in jewellery and eyewear, sustaining >30% ROE with persistent domestic institutional inflows.',
  },
  {
    ticker: 'CHOLAFIN',
    name: 'Cholamandalam Inv & Fin',
    sector: 'Financial Services',
    compositeScore: 85,
    roe: 20.2,
    debtToEquity: 0.78,
    pegRatio: 1.20,
    salesCagr3Y: 22.5,
    fiiDiiStake: '44.8% (+1.8% QoQ)',
    thesis: 'Leading underwriting discipline in vehicle financing, expanding rural loan books, and consecutive quarters of FII accumulation.',
  },
];

export default function LongTermBetsPage() {
  return (
    <article className="max-w-4xl mx-auto space-y-12 pb-20 font-serif text-[var(--color-ink)] leading-relaxed">
      <BetsNav />

      {/* Title & Metadata Header */}
      <header className="space-y-3">
        <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-[var(--color-ink)] leading-tight">
          Strategic Equity Models: Multi-Factor Quality-Growth Scoring and Capital Efficiency
        </h1>
        <p className="font-mono text-xs text-[var(--color-muted)]">
          Horizon: 3 to 12 Months · Selection Universe: NIFTY 100 &amp; NIFTY Midcap 50 · Rebalance: Monthly Post-Earnings
        </p>
      </header>

      {/* Abstract */}
      <section className="border-l-2 border-[var(--color-ink)] pl-4 italic text-sm text-[var(--color-muted)]">
        <p>
          Abstract—Long-term investment alpha cannot be generated by summarizing news headlines or prompting
          chat models for consensus stock picks. Sustainable shareholder returns over 3 to 12-month horizons are driven
          by quantifiable economic moats: high incremental return on invested capital, conservative debt structures,
          reasonable entry valuations, and accumulating institutional sponsorship. This paper presents the mathematical
          specifications for Kosh&apos;s strategic multi-factor scoring model (Score<sub>LT</sub>) and the structural
          invalidation rules governing position longevity.
        </p>
      </section>

      {/* Section I */}
      <section className="space-y-4">
        <h2 className="text-base font-mono font-bold uppercase tracking-wider text-[var(--color-ink)] border-b border-[var(--color-hairline)] pb-1">
          I. The Compounding Equation
        </h2>
        <p className="text-base text-justify">
          Over horizons exceeding two quarters, stock price returns converge to earnings growth plus dividend yield,
          bounded by valuation multiple expansion or contraction:
        </p>
        <div className="font-mono text-xs text-[var(--color-ink)] py-1 pl-4 border-l border-[var(--color-hairline)]">
          Total Return &asymp; ROE &times; (1 &minus; Payout Ratio) &plusmn; &Delta;[ P / E Multiple ]
        </div>
        <p className="text-sm text-justify text-[var(--color-muted)]">
          To insulate our strategic portfolio from multiple compression while maximizing organic earnings growth,
          we screen for companies whose reinvestment rate generates a return on equity exceeding 18% with debt-to-equity
          strictly below 0.50x.
        </p>
      </section>

      {/* Section II */}
      <section className="space-y-6">
        <h2 className="text-base font-mono font-bold uppercase tracking-wider text-[var(--color-ink)] border-b border-[var(--color-hairline)] pb-1">
          II. The Multi-Factor Scoring Specifications (0–100 Scale)
        </h2>

        <p className="text-sm text-justify">
          Every equity passing our liquidity filter (Market Capitalization &gt; ₹20,000 cr, Average Daily Turnover &gt; ₹50 cr)
          is evaluated across four independent quantitative factors, yielding a single composite score:
        </p>

        <div className="font-mono text-xs text-[var(--color-ink)] py-2 pl-4 border-l border-[var(--color-hairline)]">
          Score<sub>LT</sub> = 0.30 &times; S<sub>ROE</sub> + 0.25 &times; S<sub>D/E</sub> + 0.25 &times; S<sub>Valuation</sub> + 0.20 &times; S<sub>Institutional</sub>
        </div>

        <div className="space-y-6 pt-2 text-sm text-[var(--color-ink)]">
          {/* Factor 1 */}
          <div className="space-y-1.5">
            <h3 className="font-mono text-xs font-bold uppercase tracking-wider text-[var(--color-ink)]">
              1. Capital Efficiency &amp; Reinvestment (Weight: 30%)
            </h3>
            <p className="text-xs text-[var(--color-muted)] text-justify">
              Measures management&apos;s ability to deploy shareholder capital into high-margin operations.
            </p>
            <div className="font-mono text-xs pl-4 border-l border-[var(--color-hairline)] space-y-1">
              <div>S<sub>ROE</sub> = 100 &nbsp;if Return on Equity &ge; 18.0% and ROCE &ge; 20.0%</div>
              <div>S<sub>ROE</sub> = 60 &nbsp;&nbsp;if 12.0% &le; Return on Equity &lt; 18.0%</div>
              <div>S<sub>ROE</sub> = 0 &nbsp;&nbsp;&nbsp;if Return on Equity &lt; 12.0%</div>
            </div>
          </div>

          {/* Factor 2 */}
          <div className="space-y-1.5">
            <h3 className="font-mono text-xs font-bold uppercase tracking-wider text-[var(--color-ink)]">
              2. Balance Sheet Resilience &amp; Cash Quality (Weight: 25%)
            </h3>
            <p className="text-xs text-[var(--color-muted)] text-justify">
              Ensures solvent operations through macroeconomic tightening. Enforces a cash quality gate where operating
              cash flow must represent at least 85% of reported net income.
            </p>
            <div className="font-mono text-xs pl-4 border-l border-[var(--color-hairline)] space-y-1">
              <div>S<sub>D/E</sub> = 100 &nbsp;if Debt-to-Equity &le; 0.50x and OCF / PAT &ge; 0.85</div>
              <div>S<sub>D/E</sub> = 60 &nbsp;&nbsp;if 0.50x &lt; Debt-to-Equity &le; 1.00x</div>
              <div>S<sub>D/E</sub> = 0 &nbsp;&nbsp;&nbsp;if Debt-to-Equity &gt; 1.00x or net cash flow is negative</div>
            </div>
          </div>

          {/* Factor 3 */}
          <div className="space-y-1.5">
            <h3 className="font-mono text-xs font-bold uppercase tracking-wider text-[var(--color-ink)]">
              3. Valuation Margin of Safety (Weight: 25%)
            </h3>
            <p className="text-xs text-[var(--color-muted)] text-justify">
              Avoids expensive momentum traps by ensuring growth is purchased at an attractive price-to-earnings-to-growth ratio.
            </p>
            <div className="font-mono text-xs pl-4 border-l border-[var(--color-hairline)] space-y-1">
              <div>S<sub>Val</sub> = 100 &nbsp;if PEG Ratio &le; 1.25 or P/E &le; 3-Year Median Historical P/E</div>
              <div>S<sub>Val</sub> = 50 &nbsp;&nbsp;if 1.25 &lt; PEG Ratio &le; 1.75</div>
              <div>S<sub>Val</sub> = 0 &nbsp;&nbsp;&nbsp;if PEG Ratio &gt; 1.75</div>
            </div>
          </div>

          {/* Factor 4 */}
          <div className="space-y-1.5">
            <h3 className="font-mono text-xs font-bold uppercase tracking-wider text-[var(--color-ink)]">
              4. Institutional Sponsorship &amp; Accumulation (Weight: 20%)
            </h3>
            <p className="text-xs text-[var(--color-muted)] text-justify">
              Tracks smart-money footprint via official quarterly shareholding filings disclosed to the stock exchange.
            </p>
            <div className="font-mono text-xs pl-4 border-l border-[var(--color-hairline)] space-y-1">
              <div>S<sub>Inst</sub> = 100 &nbsp;if Combined FII + DII holding increased for &ge; 2 consecutive quarters</div>
              <div>S<sub>Inst</sub> = 50 &nbsp;&nbsp;if Institutional holding is stable (&plusmn;0.25% variance)</div>
              <div>S<sub>Inst</sub> = 0 &nbsp;&nbsp;&nbsp;if Net institutional liquidation exceeds 0.50%</div>
            </div>
          </div>
        </div>

        <p className="text-sm font-serif italic text-[var(--color-muted)] pt-2">
          Threshold Rule: Only companies securing a Composite Score<sub>LT</sub> &ge; 80 are admitted into the active portfolio candidate pool.
        </p>
      </section>

      {/* Section III */}
      <section className="space-y-4">
        <h2 className="text-base font-mono font-bold uppercase tracking-wider text-[var(--color-ink)] border-b border-[var(--color-hairline)] pb-1">
          III. Structural Invalidation Protocols
        </h2>
        <p className="text-sm text-justify">
          Strategic holdings are not traded on short-term market fluctuations. However, position discipline requires
          unambiguous quantitative exit triggers:
        </p>
        <ul className="list-disc list-inside space-y-2 text-sm text-[var(--color-ink)] pl-2">
          <li>
            <strong>Fundamental Invalidation:</strong> If trailing annualized ROE falls below 12.0% for two consecutive
            reporting quarters, or Debt-to-Equity rises above 1.0x due to unhedged borrowings, the core thesis is declared
            invalid and the equity is liquidated.
          </li>
          <li>
            <strong>Technical Regime Break:</strong> A weekly candle close exceeding 4.0% below the 200-day Simple Moving
            Average triggers an automatic structural review to prevent riding protracted multi-year bear regimes.
          </li>
          <li>
            <strong>Target Multiple Realization:</strong> Positions are trimmed when the trailing P/E multiple expands
            beyond 1.5x the company&apos;s 5-year historical median, reallocating capital into newly qualified candidates.
          </li>
        </ul>
      </section>

      {/* Section IV */}
      <section className="space-y-4">
        <h2 className="text-base font-mono font-bold uppercase tracking-wider text-[var(--color-ink)] border-b border-[var(--color-hairline)] pb-1">
          IV. Active Strategic Candidate Ledger
        </h2>
        <p className="text-xs font-mono text-[var(--color-muted)]">
          Table 1: Current strategic equities meeting Score<sub>LT</sub> &ge; 80 (Screening Universe: NIFTY 100 &amp; Midcap 50).
        </p>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs font-mono border-t border-b border-[var(--color-ink)]">
            <thead>
              <tr className="border-b border-[var(--color-hairline)] text-[10px] uppercase text-[var(--color-muted)]">
                <th className="py-2 pr-3 font-semibold">Ticker</th>
                <th className="py-2 pr-3 font-semibold">Sector</th>
                <th className="py-2 pr-3 text-right font-semibold">Score</th>
                <th className="py-2 pr-3 text-right font-semibold">ROE</th>
                <th className="py-2 pr-3 text-right font-semibold">D / E</th>
                <th className="py-2 pr-3 text-right font-semibold">PEG</th>
                <th className="py-2 pr-3 text-right font-semibold">3Y Sales CAGR</th>
                <th className="py-2 pr-3 text-right font-semibold">Inst. Stake</th>
                <th className="py-2 font-semibold min-w-[200px]">Strategic Thesis</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[var(--color-hairline)]">
              {SAMPLE_STRATEGIC_SETUPS.map((s) => (
                <tr key={s.ticker}>
                  <td className="py-2.5 pr-3">
                    <span className="font-bold text-[var(--color-ink)]">{s.ticker}</span>
                    <span className="text-[10px] text-[var(--color-muted)] block font-serif">{s.name}</span>
                  </td>
                  <td className="py-2.5 pr-3 text-[11px] text-[var(--color-muted)]">{s.sector}</td>
                  <td className="py-2.5 pr-3 text-right font-semibold tabular-nums text-[var(--color-ink)]">
                    {s.compositeScore}
                  </td>
                  <td className="py-2.5 pr-3 text-right tabular-nums text-[var(--color-ink)] font-semibold">
                    {s.roe.toFixed(1)}%
                  </td>
                  <td className="py-2.5 pr-3 text-right tabular-nums text-[var(--color-ink)]">
                    {s.debtToEquity.toFixed(2)}x
                  </td>
                  <td className="py-2.5 pr-3 text-right tabular-nums text-[var(--color-ink)]">
                    {s.pegRatio.toFixed(2)}
                  </td>
                  <td className="py-2.5 pr-3 text-right tabular-nums text-[var(--color-ink)]">
                    {s.salesCagr3Y.toFixed(1)}%
                  </td>
                  <td className="py-2.5 pr-3 text-right text-[10px] text-[var(--color-muted)]">
                    {s.fiiDiiStake}
                  </td>
                  <td className="py-2.5 text-[11px] font-serif text-[var(--color-muted)]">
                    {s.thesis}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <footer className="flex justify-between items-center text-xs font-mono text-[var(--color-muted)] pt-3">
          <span>Rebalanced monthly upon quarterly corporate filings and shareholding disclosures.</span>
          <Link href="/bets/short-term" className="underline hover:text-[var(--color-ink)]">
            &larr; Return to Short-Term Tactical Models
          </Link>
        </footer>
      </section>
    </article>
  );
}
