import type { Metadata } from 'next';
import { Fraunces, Hanken_Grotesk, JetBrains_Mono } from 'next/font/google';
import './globals.css';
import { NavBar } from '../components/NavBar';

const fraunces = Fraunces({
  subsets: ['latin'],
  variable: '--font-fraunces',
  style: ['normal', 'italic'],
  display: 'swap',
  axes: ['opsz', 'SOFT', 'WONK'],
});

const hanken = Hanken_Grotesk({
  subsets: ['latin'],
  variable: '--font-hanken',
  weight: ['400', '500', '700'],
  display: 'swap',
});

const jetbrains = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-jetbrains',
  weight: ['400', '500', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Kosh — Indian Market Intelligence',
  description: 'Daily briefings, watchlists, and research for Indian equity markets.',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${fraunces.variable} ${hanken.variable} ${jetbrains.variable}`}
    >
      <body className="bg-[var(--color-bg)] text-[var(--color-ink)] font-sans min-h-screen flex flex-col">
        {/* Masthead */}
        <header className="border-b border-[var(--color-hairline)] bg-[var(--color-surface)]">
          <div className="max-w-4xl mx-auto px-6 py-5">
            {/* Wordmark row */}
            <div className="flex items-baseline justify-between gap-4 mb-4">
              <div>
                <span
                  className="font-display text-3xl font-black tracking-tight text-[var(--color-brand)]"
                  style={{ fontOpticalSizing: 'auto' } as React.CSSProperties}
                >
                  KOSH
                </span>
                <span className="ml-3 text-xs font-sans font-medium tracking-widest uppercase text-[var(--color-faint)]">
                  Indian market intelligence
                </span>
              </div>
              {/* Today's date */}
              <time className="font-mono text-xs text-[var(--color-faint)] hidden sm:block">
                {new Date().toLocaleDateString('en-IN', {
                  weekday: 'short',
                  year: 'numeric',
                  month: 'short',
                  day: 'numeric',
                  timeZone: 'Asia/Kolkata',
                })}
              </time>
            </div>
            {/* Nav */}
            <NavBar />
          </div>
        </header>

        {/* Main content */}
        <main className="flex-1 max-w-4xl mx-auto w-full px-6 py-10">
          {children}
        </main>

        {/* Footer */}
        <footer className="border-t border-[var(--color-hairline)] bg-[var(--color-surface)] mt-auto">
          <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
            <p className="text-xs text-[var(--color-faint)] font-sans">
              Generated by GitHub Actions
            </p>
            <p className="font-mono text-xs text-[var(--color-faint)]">
              &copy; {new Date().getFullYear()} Kosh
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
